### PR TITLE
Store images and refactor db for testing

### PR DESCRIPTION
**Pull request by tinproject**

### CODE REVIEW

**Comment by tinproject** [comment]
I know there is no tests for this but review and merge please. It will fix the master branch. I will add lots of tests later today.

**Comment by jsenin** [comment]
@tinproject I have too questions about forms.
- You are using validate_on_submit()[1] that looks great for minimalize code on submiting data. But what's happens when data is not valid, it's some flash message passed to the template ?. I explain this. On this kind of forms usually we have 3 states:
- get: for retrieving the form with default data
- post: with valid data should do something and notify to the user about de successfully action.
- post: with invalid data should return to the form with submited data, providing information about the invalid fields.

With validate_on_submit() is possible to do this last option ?

- Secondly, I see at test_forms.py that this test is doing more check than the description
    def test_should_fail_if_description_is_empty(self):

        assert 'Field must be at least 5 characters long.' or 'This field is required.' \
            in project.errors['description']

is there another above test  def test_should_accept_description_greater_than_5(self)

This are my suggestions/questions .

@AlvaroCaste  could you estimate this ?
thanks


[1] http://flask-wtf.readthedocs.org/en/latest/quickstart.html#validating-forms

**Comment by AlvaroCaste** [comment]
PR so long...

**Comment by tinproject** [comment]
The [documentation of validate_on_submit](http://flask-wtf.readthedocs.org/en/latest/api.html?highlight=validate_on_submit#flask_wtf.Form.validate_on_submit) stats that validate on submit it's the same as form.is_submitted and form.validate so it's mutating the form that internally stores the errors happening on eache field. If we want to use flask flash-messages we couldnt use this helper, I though it's better this way passing the error message inside the fields.


The second question. I add DataRequired to descriprion field becouse min lenght validator aren't catching well the empty field on repost, the test fail becouse it's not the same error string from DataRequiered validator than the existing one so I add this quick and dirty condition.
This tests are the ones that we are still needing to refactor to not depend on error string, at the end this strings should be in spanish.

**Pull request merged**
